### PR TITLE
Mark `glslangValidatorMac` binary as executable

### PR DESCRIPTION
**Pull request by matt-curtis**
Fixes the issue discussed in #36 by marking the validator binary as executable using `chmod +x ...`, and committing that into the repo.

### CODE REVIEW

**Comment by racz16** [comment]
Thank you very much! I'll wait a couple of days if @Nek wants to test it, originally it was his issue #36. But if he doesn't have the time to test it, eventually I'll merge the PR, because seemingly it should work and I'm sure you tested it as well.

**Comment by Nek** [comment]
@matt-curtis thanks! How do I test it? Should I package the extension from your branch?

**Comment by matt-curtis** [comment]
@Nek that should work!

**Comment by racz16** [comment]
> @matt-curtis thanks! How do I test it? Should I package the extension from your branch?

In the repository, you can find the [build instructions](https://github.com/racz16/WebGL-GLSL-Editor/blob/master/BUILD.md) for Windows and Linux. I think you can loosely follow the Linux instructions on Mac and you don't have to package, it's enough to complete step 10. If you build it on Windows or Linux, you have to package it and copy it to a Mac device.

**Comment by racz16** [comment]
@Nek Do you have the time to check the PR? If not it's fine and I'll merge it.

**Comment by matt-curtis** [comment]
(If Nek can't test and you merge, worst case is that it _doesn't_ work for other macOS users, which doesn't change anything: it doesn't work for macOS users now either.)

**Comment by Nek** [comment]
@racz16 Sorry, I'm travelling at the moment, no.

**Comment by racz16** [comment]
> @racz16 Sorry, I'm travelling at the moment, no.

Okay, that's fine, I merge it.

**Pull request merged**
